/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.ryandens.jlink

import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertNotNull

/**
 * A simple unit test for the 'com.ryandens.jlink-jre' plugin.
 */
class JlinkJrePluginTest {
    @Test fun `plugin registers task`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("com.ryandens.jlink-jre")

        // Verify the result
        assertNotNull(project.tasks.findByName("jlinkJre"))
    }
}
